name: doesItWork
favicon: null
layout_spectrum: 1
typography_spectrum: 0.20388374803587794
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#99cc33'
    - '#ffffff'
    - '#00ff00'
    - '#808000'
    - '#000000'
  brandStrength: 1
  lightness: 0.4393611289560795
  saturation: 0.6858215355314314
  rhythmicContrast: 0.48311140039004385
purpose: []
